/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    BaseForm: typeof import('./src/components/form/BaseForm.vue')['default']
    DemoChild: typeof import('./src/components/globalComponents/DemoChild.vue')['default']
    DemoParent: typeof import('./src/components/globalComponents/DemoParent.vue')['default']
    Hello: typeof import('./src/components/globalComponents/Hello.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
