/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseForm: typeof import('./src/components/form/BaseForm.vue')['default']
    DemoChild: typeof import('./src/components/globalComponents/DemoChild.vue')['default']
    DemoParent: typeof import('./src/components/globalComponents/DemoParent.vue')['default']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
